name: CI-CD

on:
    push:
        branches:
            - main
jobs:
    test:
        name: Running unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.11.1
              uses: actions/setup-node@v4
              with:
                node-version: '20.11.1'

            - name: Install dependencies
              run: |
                cd backend
                npm i

            - name: Run unit tests
              run: |
                cd backend
                npm run test

            - uses: actions/upload-artifact@v4
              if: failure()
              with:
                name: Report if failure
                path: |
                  /home/runner/work/C214_L1_Projeto/C214_L1_Projeto/backend/jest-html-reporters-attach
                  /home/runner/work/C214_L1_Projeto/C214_L1_Projeto/backend/jest_html_reporters.html
                  - name: Test Results

            - uses: actions/upload-artifact@v4
              with:
                name: Report if success
                path: |
                  /home/runner/work/C214_L1_Projeto/C214_L1_Projeto/backend/jest-html-reporters-attach
                  /home/runner/work/C214_L1_Projeto/C214_L1_Projeto/backend/jest_html_reporters.html
                  - name: Test Results